project:
  type: website
  output-dir: _site
 
website:
  title: "My Website"
 
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: projects.qmd
        text: Projects
      - href: fallplot.qmd
        text: Fall
 
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
 
editor: visual